services:
  simplify-drowsiness-detector:
    build:
      context: .
      dockerfile: Dockerfile
    image: simplify-drowsiness-detector
    container_name: simplify-drowsiness-detector
    restart: unless-stopped
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - 8002:8002
    networks:
      - proxy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
          # Ensure container has enough CPU and memory for worker threads
          cpus: '4'
          memory: 6G
    runtime: nvidia
    # Ensure proper signal handling
    init: true
    stop_signal: SIGINT
    stop_grace_period: 30s

networks:
  proxy:
    external: true